### PR TITLE
Add `timeout` and `interval` functions.

### PR DESCRIPTION
**Pull request by TyOverby**
I tried adding functions that I need for my async code to be pretty.

`Future::timeout` creates a `Future<(), ()>` that will be completed after a certain amount of time has passed.

`Stream::interval` creates `Stream<(), ()>` that is completed repeatedly every `n` milliseconds.  

I think that both function implementations are correct, but I'm at a loss for how to go about writing more tests.

### CODE REVIEW

**Comment by carllerche** [comment]
I do what a timeout feature, however this will spawn a new thread every time a timeout is requested. Perhaps there would be an option to use a single thread to manage all the timeouts. I know that syncbox has a pending PR to bring in a scheduled thread pool (https://github.com/carllerche/syncbox/pull/5) but it needs some love.

**Comment by TyOverby** [comment]
As far as I know, the only way to have a single thread handle all of it would be if that thread were running a proto event loop.

**Comment by carllerche** [comment]
A scheduled thread pool could do it :) I will see if I can get that PR (the one in syncbox) cleaned up this weekend.

**Comment by TyOverby** [comment]
Cool, I'll close this PR and make an issue for it!

**Pull request closed without merging**
