### PR TITLE
Pooled futures

### PR DESCRIPTION
**Pull request by posix4e**
```
Allow defer or background on a threadpool
```

### CODE REVIEW

**Comment by posix4e** [comment]
Dependent on https://github.com/carllerche/syncbox/pull/23 to pass

**Comment by carllerche** [comment]
I merged the stuff to Syncbox. I haven't tried running this PR yet. Just skimming it, it looks mostly fine, but we can't include features (fnbox here) as I would like to target stable rust releases. Just at a glance, I don't see why it is really necessary. I believe you should be able to accept an `FnOnce` instead of an `FnBox`.

**Comment by posix4e** [comment]
Agreed. I'll change it soon.

On Fri, Jul 3, 2015, 18:46 Carl Lerche notifications@github.com wrote:

> I merged the stuff to Syncbox. I haven't tried running this PR yet. Just
> skimming it, it looks mostly fine, but we can't include features (fnbox
> here) as I would like to target stable rust releases. Just at a glance, I
> don't see why it is really necessary. I believe you should be able to
> accept an FnOnce instead of an FnBox.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/carllerche/eventual/pull/23#issuecomment-118438169.
> 
> ## 

Sent from my mobile 5045076749
Alex Newman

**Comment by posix4e** [comment]
I forgot you can () closures! Rebased and repushed

**Comment by posix4e** [comment]
I have gotten rid of the fnbox. Should be all stable now

**Comment by carllerche** [comment]
woohoo, finally merged!

**Pull request merged**
