### PR TITLE
Add a defer task

### PR DESCRIPTION
**Pull request by posix4e**
I am going to merge this one at a time. We can keep the issue open for background though.

### CODE REVIEW

**Comment by posix4e** [comment]
-1 this for a bit. I want to see if I can improve it.

**Comment by posix4e** [comment]
So rethinking this, I think the requirement of cloning the pool seems like a misapi. Should we change threadpool so we don't require this?

**Comment by carllerche** [comment]
Which `clone()` are you referring to specifically?

**Comment by posix4e** [comment]
``` rust
let res = eventual::defer(pool.clone() <----this, future).and_then( | v: i32 | {
    // Assert thread local is not present here
    Ok(v + 5)
});
```

**Comment by posix4e** [comment]
I haven't been able to figure out a good way to require the clone at compile time or tie the scope of the threadpool to the return complete object. Ideally we could have one of them refer to each other. An alternative would be returning a struct which contains both elements. Returning them both as a tuple doesn't seem to help at all unless the thread_pool stays in scope until the .complete runs.

**Comment by posix4e** [comment]
I added support for the background task as well.

**Comment by posix4e** [comment]
I should point out this passed only with the unstable rust build.

**Pull request closed without merging**
